# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6bba2997c44b2d05d46270cce49bc62022ade904795040058fc5b3a53a59cb7e4b277bbd63880cb4552a312de8d978928c0c9899063e41a4fa2b8cc0171ec5fe

test:
  secret_key_base: 76757f4641b8368d99fc9e736e4f003ab8e2ab5a9af9c35db20f2d6ceef0bb9b63c8ce17e19ea88398e6d64b2981ea15a5f8df4b6b1d7af7e8b3c31f0f50727e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
